package com.productlist.nativekeystore

import android.content.Context
import android.content.SharedPreferences
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.facebook.react.bridge.*
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.TurboModule
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import java.util.Base64
import com.productlist.nativekeystore.NativeKeyStoreSpec
import android.util.Log

// This interface is generated by Codegen - DO NOT MODIFY MANUALLY
// But for completeness, here's what it expects
@ReactModule(name = NativeKeyStoreModule.NAME)
class NativeKeyStoreModule(
    private val reactContext: ReactApplicationContext
) : NativeKeyStoreSpec(reactContext) {

    private val sharedPrefs: SharedPreferences =
        reactContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    override fun getName(): String = NAME

    // TurboModule methods - NO @ReactMethod annotations!

    override fun setRefreshToken(password: String, promise: Promise) {
        try {

            val encryptedPassword = encryptWithKeystore(password)
            log("Encrypted password: $encryptedPassword")

            sharedPrefs.edit().apply {
                putString(REFRESH_ENC, encryptedPassword)
                apply()
            }
            promise.resolve(true)
        } catch (e: Exception) {
            promise.reject("KEYCHAIN_ERROR", e.message, e)
        }
    }

    override fun getRefreshToken(promise: Promise) {
        try {
            val encryptedPassword = sharedPrefs.getString(REFRESH_ENC, null)
            log("Get encrypted refresh token: $encryptedPassword")
            if (encryptedPassword != null) {
                val password = decryptWithKeystore(encryptedPassword)
                log("Get refresh token: $password")
                val result = Arguments.createMap()
                result.putString("token", password)
                promise.resolve(result)
            } else {
                promise.resolve(null)
            }
        } catch (e: Exception) {
            promise.reject("KEYCHAIN_ERROR", e.message, e)
        }
    }

    override fun setGenericPassword(password: String, promise: Promise) {
        try {
            val encryptedPassword = encryptWithKeystore(password)
            log("Encrypted password: $encryptedPassword")

            sharedPrefs.edit().apply {
                putString(PASSWORD_ENC, encryptedPassword)
                apply()
            }
            promise.resolve(true)
        } catch (e: Exception) {
            promise.reject("KEYCHAIN_ERROR", e.message, e)
        }
    }


    override fun getGenericPassword(promise: Promise) {
        try {
            val encryptedPassword = sharedPrefs.getString(PASSWORD_ENC, null)
            log("Get encrypted password: $encryptedPassword")
            if (encryptedPassword != null) {
                val password = decryptWithKeystore(encryptedPassword)
                log("Get password: $password")
                val result = Arguments.createMap()
                result.putString("password", password)
                promise.resolve(result)
            } else {
                promise.resolve(null)
            }
        } catch (e: Exception) {
            promise.reject("KEYCHAIN_ERROR", e.message, e)
        }
    }

    override fun resetGenericPassword(promise: Promise) {
        try {
            sharedPrefs.edit().clear().apply()

            if (Build.VERSION.SDK_INT >= ANDROID_API_M) {
                val keyStore = KeyStore.getInstance(ANDROID_KEY_STORE)
                keyStore.load(null)
                keyStore.deleteEntry(KEY_ALIAS)
            }

            promise.resolve(true)
        } catch (e: Exception) {
            promise.reject("KEYCHAIN_ERROR", e.message, e)
        }
    }

    // Keystore encryption methods (API 23+)
    @Throws(Exception::class)
    private fun encryptWithKeystore(plainText: String): String {
        val keyStore = KeyStore.getInstance(ANDROID_KEY_STORE)
        keyStore.load(null)

        val secretKey = getOrCreateSecretKey()

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)

        val iv = cipher.iv
        val encryption = cipher.doFinal(plainText.toByteArray(Charsets.UTF_8))

        // Combine IV and encrypted data
        val combined = iv + encryption
        return android.util.Base64.encodeToString(combined, android.util.Base64.DEFAULT)
    }

    @Throws(Exception::class)
    private fun decryptWithKeystore(encryptedData: String): String {
        val keyStore = KeyStore.getInstance(ANDROID_KEY_STORE)
        keyStore.load(null)

        val secretKey = keyStore.getKey(KEY_ALIAS, null) as SecretKey

        val decoded = android.util.Base64.decode(encryptedData, android.util.Base64.DEFAULT)

        // Extract IV (first 12 bytes for GCM)
        val iv = decoded.copyOfRange(0, 12)
        val cipherText = decoded.copyOfRange(12, decoded.size)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(128, iv)
        cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)

        val decrypted = cipher.doFinal(cipherText)
        return String(decrypted, Charsets.UTF_8)
    }

    @Throws(Exception::class)
    private fun getOrCreateSecretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEY_STORE)
        keyStore.load(null)

        var secretKey = keyStore.getKey(KEY_ALIAS, null) as? SecretKey

        if (secretKey == null) {
            val keyGenerator = KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES,
                ANDROID_KEY_STORE
            )

            val keyGenParameterSpec = KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setRandomizedEncryptionRequired(true)
                .build()

            keyGenerator.init(keyGenParameterSpec)
            secretKey = keyGenerator.generateKey()
        }

        return secretKey
    }

    private fun log(s: String) {
        Log.d("NativeKeyStore", s)
    }

    companion object {
        const val NAME = "NativeKeyStore"
        private const val PREFS_NAME = "secure_prefs"
        private const val KEY_ALIAS = "com.productlist.nativekeystore.KEY_ALIAS"
        private const val ANDROID_KEY_STORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val ANDROID_API_M = 23
        private const val PASSWORD_ENC = "password_enc"
        private const val REFRESH_ENC = "refresh_token_enc"

    }
}